name: CI (ARCADE)

on: [push]

jobs:

  build-windows-gcc:
    runs-on: windows-latest
    concurrency:
      group: ${{ github.ref }}
      cancel-in-progress: true
    defaults:
      run:
        shell: msys2 {0}
    steps:
    - uses: msys2/setup-msys2@v2
      with:
        install: git make mingw-w64-x86_64-gcc mingw-w64-x86_64-python mingw-w64-x86_64-lld mingw-w64-x86_64-libc++
    - uses: actions/checkout@master
    - name: Build
      env:
        MINGW64: "/mingw64"
        PTR64: "1"
      run: make -j2 PTR64=1 SUBTARGET=arcade OSD=winui DEPRECATED=0 SYMBOLS=0 NO_SYMBOLS=1
    - uses: actions/upload-artifact@master
      with:
        name: arcade64-windows-gcc-${{ github.sha }}
        path: arcade64.exe
